<?php

namespace org\unece\uncefact;

use oihana\reflect\traits\ConstantsTrait;

/**
 * UN/CEFACT Unit of Measure Symbols Enumeration Class (Recommendation 20).
 *
 * This class exposes an extended selection of the most commonly used codes across
 * various commercial and logistical contexts.
 *
 * It mirrors {@see MeasureCode} and {@see MeasureName} : the three classes declare
 * the same constant names, which is what the cross lookups rely on.
 *
 * ⚠️ Generated by tools/generate-uncefact-rec20.php — do not edit by hand.
 * Edit tools/data/uncefact-rec20-selection.csv and run the generator instead.
 *
 * @see https://unece.org/trade/uncefact/cl-recommendations
 */
class MeasureSymbol
{
    use ConstantsTrait
    {
        resetCaches as internalResetCaches ;
    }

    // =====================================================================
    // Area Units
    // =====================================================================

    public const string ACRE                     = 'ac' ; // Acre
    public const string ACRE_FOOT                = 'ac-ft' ; // Acre-Foot
    public const string HECTARE                  = 'ha' ; // Hectare
    public const string SQUARE_CENTIMETER        = 'cm²' ; // Square Centimeter
    public const string SQUARE_DECIMETER         = 'dm²' ; // Square Decimeter
    public const string SQUARE_FOOT              = 'ft²' ; // Square Foot
    public const string SQUARE_INCH              = 'in²' ; // Square Inch
    public const string SQUARE_KILOMETER         = 'km²' ; // Square Kilometer
    public const string SQUARE_METER             = 'm²' ; // Square Meter
    public const string SQUARE_MILE              = 'mi²' ; // Square Mile
    public const string SQUARE_MILLIMETER        = 'mm²' ; // Square Millimeter
    public const string SQUARE_YARD              = 'yd²' ; // Square Yard

    // =====================================================================
    // Common Miscellaneous Units
    // =====================================================================

    public const string AMPERE                   = 'A' ; // Ampere
    public const string BECQUEREL                = 'Bq' ; // Becquerel
    public const string BIT                      = 'bit' ; // Bit
    public const string BYTE                     = 'B' ; // Byte
    public const string COULOMB                  = 'C' ; // Coulomb
    public const string DECIBEL                  = 'dB' ; // Decibel
    public const string FARAD                    = 'F' ; // Farad
    public const string GIGABYTE                 = 'GB' ; // Gigabyte
    public const string GRAY                     = 'Gy' ; // Gray
    public const string HENRY                    = 'H' ; // Henry
    public const string HERTZ                    = 'Hz' ; // Hertz
    public const string KILOBYTE                 = 'KB' ; // Kilobyte
    public const string KILOHERTZ                = 'kHz' ; // Kilohertz
    public const string KILOWATT                 = 'kW' ; // Kilowatt
    public const string LUMEN                    = 'lm' ; // Lumen
    public const string LUX                      = 'lx' ; // Lux
    public const string MEGABYTE                 = 'MB' ; // Megabyte
    public const string MEGAHERTZ                = 'MHz' ; // Megahertz
    public const string NEWTON                   = 'N' ; // Newton
    public const string OHM                      = 'Ω' ; // Ohm
    public const string POUND_FORCE              = 'lbf' ; // Pound-force
    public const string REVOLUTION_PER_MINUTE    = 'rpm' ; // Revolution per Minute
    public const string SIEMENS                  = 'S' ; // Siemens
    public const string SIEVERT                  = 'Sv' ; // Sievert
    public const string TESLA                    = 'T' ; // Tesla
    public const string VOLT                     = 'V' ; // Volt
    public const string WATT                     = 'W' ; // Watt
    public const string WEBER                    = 'Wb' ; // Weber

    // =====================================================================
    // Degrees Units
    // =====================================================================

    public const string ANGULAR                  = '°' ; // Angular Degree
    public const string RADIAN                   = 'rad' ; // Radian

    // =====================================================================
    // Pressure Units
    // =====================================================================

    public const string BAR                      = 'bar' ; // Bar
    public const string MILLIBAR                 = 'mbar' ; // Millibar
    public const string PASCAL                   = 'Pa' ; // Pascal
    public const string POUND_PER_SQUARE_INCH    = 'psi' ; // Pound per Square Inch

    // =====================================================================
    // Volume Units
    // =====================================================================

    public const string BARREL                   = 'bbl' ; // Barrel
    public const string CENTILITRE               = 'cL' ; // Centilitre
    public const string CUBIC_CENTIMETER         = 'cm³' ; // Cubic Centimeter
    public const string CUBIC_DECIMETER          = 'dm³' ; // Cubic Decimeter
    public const string CUBIC_FOOT               = 'ft³' ; // Cubic Foot
    public const string CUBIC_METER              = 'm³' ; // Cubic Meter
    public const string IMPERIAL_GALLON          = 'gal (Imp)' ; // Imperial Gallon
    public const string LITER                    = 'L' ; // Liter
    public const string MILLILITER               = 'mL' ; // Milliliter
    public const string US_GALLON                = 'gal (US)' ; // US Gallon

    // =====================================================================
    // Energy Units
    // =====================================================================

    public const string CALORIE                  = 'cal' ; // Calorie
    public const string JOULE                    = 'J' ; // Joule
    public const string KILOCALORIE              = 'kcal' ; // Kilocalorie
    public const string KILOJOULE                = 'kJ' ; // Kilojoule
    public const string KILOWATT_HOUR            = 'kWh' ; // Kilowatt-Hour

    // =====================================================================
    // Mass Units (Weight)
    // =====================================================================

    public const string CARAT                    = 'ct' ; // Carat
    public const string GRAM                     = 'g' ; // Gram
    public const string KILOGRAM                 = 'kg' ; // Kilogram
    public const string METRIC_TON               = 't' ; // Metric Ton
    public const string MILLIGRAM                = 'mg' ; // Milligram
    public const string OUNCE                    = 'oz' ; // Ounce
    public const string POUND                    = 'lb' ; // Pound

    // =====================================================================
    // Temperature Units
    // =====================================================================

    public const string CELSIUS                  = '°C' ; // Degree Celsius
    public const string FAHRENHEIT               = '°F' ; // Degree Fahrenheit
    public const string KELVIN                   = 'K' ; // Kelvin

    // =====================================================================
    // Length Units
    // =====================================================================

    public const string CENTIMETER               = 'cm' ; // Centimeter
    public const string FOOT                     = 'ft' ; // Foot
    public const string HECTOMETER               = 'hm' ; // Hectometer
    public const string INCH                     = 'in' ; // Inch
    public const string KILOMETER                = 'km' ; // Kilometer
    public const string METER                    = 'm' ; // Meter
    public const string MILE                     = 'mi' ; // Mile
    public const string MILLIMETER               = 'mm' ; // Millimeter
    public const string YARD                     = 'yd' ; // Yard

    // =====================================================================
    // Time Units
    // =====================================================================

    public const string DAY                      = 'day' ; // Day
    public const string HOUR                     = 'h' ; // Hour
    public const string MINUTE                   = 'min' ; // Minute
    public const string MONTH                    = 'month' ; // Month
    public const string SECOND                   = 's' ; // Second
    public const string WEEK                     = 'wk' ; // Week
    public const string YEAR                     = 'yr' ; // Year

    // =====================================================================
    // Quantity Units (Unités de quantité)
    // =====================================================================

    public const string DOZEN                    = 'dz' ; // Dozen
    public const string GROSS                    = 'gr' ; // Gross
    public const string HUNDRED                  = '100' ; // Hundred
    public const string PAIR                     = 'pr' ; // Pair
    public const string PIECE                    = 'pc' ; // Piece
    public const string TEN_PAIRS                = '10pr' ; // Ten Pairs
    public const string THOUSAND                 = '1000' ; // Thousand
    public const string UNIT                     = 'un' ; // Unit

    // =====================================================================
    // Density Units
    // =====================================================================

    public const string KILOGRAM_PER_CUBIC_METER = 'kg/m³' ; // Kilogram per cubic metre

    // =====================================================================
    // Percentage and Ratio Units
    // =====================================================================

    public const string PARTS_PER_MILLION        = 'ppm' ; // Parts Per Million
    public const string PERCENT                  = '%' ; // Percent
    public const string PER_THOUSAND             = '‰' ; // Per Thousand

    // =====================================================================
    // Generic / Dimensionless Units & Factors
    // =====================================================================

    public const string SCORE                    = 'score' ; // Score

    // =====================================================================
    // Private
    // =====================================================================

    private static ?array $CODES = null ;
    private static ?array $NAMES = null ;

    // =====================================================================
    // Methods
    // =====================================================================

    /**
     * Returns the official UN/CEFACT code for a given symbol.
     * @param string $symbol The UN/CEFACT symbol (e.g., 'kg').
     * @return string|null The UN/CEFACT code (e.g., 'KGM') or null if not found.
     */
    public static function getCode( string $symbol ): ?string
    {
        if( static::$CODES === null )
        {
            static::$CODES = MeasureCode::getAll() ;
        }
        return static::$CODES[ self::getConstant( $symbol ) ] ?? null;
    }

    /**
     * Returns the official UN/CEFACT name for a given symbol.
     * @param string $symbol The UN/CEFACT symbol (e.g., 'kg').
     * @return string|null The UN/CEFACT name (e.g., 'Kilogram') or null if not found.
     */
    public static function getName( string $symbol ): ?string
    {
        if( static::$NAMES === null )
        {
            static::$NAMES = MeasureName::getAll() ;
        }
        return static::$NAMES[ self::getConstant( $symbol ) ] ?? null;
    }

    /**
     * Returns the symbol matching a specific unit code.
     * @param string $code The UN/CEFACT code (e.g., 'KGM').
     * @return string|null The UN/CEFACT symbol (e.g., 'kg') or null if not found.
     */
    public static function getFromCode( string $code ): ?string
    {
        return MeasureCode::getSymbol( $code ) ;
    }

    /**
     * Returns the symbol matching a specific unit name.
     * @param string $name The UN/CEFACT name (e.g., 'Kilogram').
     * @return string|null The UN/CEFACT symbol (e.g., 'kg') or null if not found.
     */
    public static function getFromName( string $name ): ?string
    {
        return MeasureName::getSymbol( $name ) ;
    }

    /**
     * Reset the internal cache of the static methods.
     * @return void
     */
    public static function resetCaches(): void
    {
        static::internalResetCaches();
        static::$CODES = null ;
        static::$NAMES = null ;
    }
}
