<?php

namespace org\unece\uncefact;

use oihana\reflect\traits\ConstantsTrait;

/**
 * UN/CEFACT Unit of Measure Codes Enumeration Class (Recommendation 20).
 *
 * This class exposes an extended selection of the most commonly used codes across
 * various commercial and logistical contexts.
 *
 * It mirrors {@see MeasureName} and {@see MeasureSymbol} : the three classes declare
 * the same constant names, which is what the cross lookups rely on.
 *
 * ⚠️ Generated by tools/generate-uncefact-rec20.php — do not edit by hand.
 * Edit tools/data/uncefact-rec20-selection.csv and run the generator instead.
 *
 * @see https://unece.org/trade/uncefact/cl-recommendations
 */
class MeasureCode
{
    use ConstantsTrait
    {
        resetCaches as internalResetCaches ;
    }

    // =====================================================================
    // Area Units
    // =====================================================================

    public const string ACRE                     = 'ACR' ; // Acre
    public const string ACRE_FOOT                = 'M67' ; // Acre-Foot
    public const string HECTARE                  = 'HAR' ; // Hectare
    public const string SQUARE_CENTIMETER        = 'CMK' ; // Square Centimeter
    public const string SQUARE_DECIMETER         = 'DMK' ; // Square Decimeter
    public const string SQUARE_FOOT              = 'FTK' ; // Square Foot
    public const string SQUARE_INCH              = 'INK' ; // Square Inch
    public const string SQUARE_KILOMETER         = 'KMK' ; // Square Kilometer
    public const string SQUARE_METER             = 'MTK' ; // Square Meter
    public const string SQUARE_MILE              = 'MIK' ; // Square Mile
    public const string SQUARE_MILLIMETER        = 'MMK' ; // Square Millimeter
    public const string SQUARE_YARD              = 'YDK' ; // Square Yard

    // =====================================================================
    // Common Miscellaneous Units
    // =====================================================================

    public const string AMPERE                   = 'AMP' ; // Ampere
    public const string BECQUEREL                = 'BQL' ; // Becquerel
    public const string BIT                      = 'A99' ; // Bit
    public const string BYTE                     = 'AD' ; // Byte
    public const string COULOMB                  = 'COU' ; // Coulomb
    public const string DECIBEL                  = '2N' ; // Decibel
    public const string FARAD                    = 'FAR' ; // Farad
    public const string GIGABYTE                 = 'E34' ; // Gigabyte
    public const string GRAY                     = 'A95' ; // Gray
    public const string HENRY                    = '81' ; // Henry
    public const string HERTZ                    = 'HTZ' ; // Hertz
    public const string KILOBYTE                 = '2P' ; // Kilobyte
    public const string KILOHERTZ                = 'KHZ' ; // Kilohertz
    public const string KILOWATT                 = 'KWT' ; // Kilowatt
    public const string LUMEN                    = 'LUM' ; // Lumen
    public const string LUX                      = 'LUX' ; // Lux
    public const string MEGABYTE                 = '4L' ; // Megabyte
    public const string MEGAHERTZ                = 'MHZ' ; // Megahertz
    public const string NEWTON                   = 'NEW' ; // Newton
    public const string OHM                      = 'OHM' ; // Ohm
    public const string POUND_FORCE              = 'C78' ; // Pound-force
    public const string REVOLUTION_PER_MINUTE    = 'RPM' ; // Revolution per Minute
    public const string SIEMENS                  = 'SIE' ; // Siemens
    public const string SIEVERT                  = 'D13' ; // Sievert
    public const string TESLA                    = 'D33' ; // Tesla
    public const string VOLT                     = 'VLT' ; // Volt
    public const string WATT                     = 'WTT' ; // Watt
    public const string WEBER                    = 'WEB' ; // Weber

    // =====================================================================
    // Degrees Units
    // =====================================================================

    public const string ANGULAR                  = 'DD' ; // Angular Degree
    public const string RADIAN                   = 'C81' ; // Radian

    // =====================================================================
    // Pressure Units
    // =====================================================================

    public const string BAR                      = 'BAR' ; // Bar
    public const string MILLIBAR                 = 'MBR' ; // Millibar
    public const string PASCAL                   = 'PAL' ; // Pascal
    public const string POUND_PER_SQUARE_INCH    = 'PS' ; // Pound per Square Inch

    // =====================================================================
    // Volume Units
    // =====================================================================

    public const string BARREL                   = 'BLL' ; // Barrel
    public const string CENTILITRE               = 'CLT' ; // Centilitre
    public const string CUBIC_CENTIMETER         = 'CMQ' ; // Cubic Centimeter
    public const string CUBIC_DECIMETER          = 'DMQ' ; // Cubic Decimeter
    public const string CUBIC_FOOT               = 'FTQ' ; // Cubic Foot
    public const string CUBIC_METER              = 'MTQ' ; // Cubic Meter
    public const string IMPERIAL_GALLON          = 'GLI' ; // Imperial Gallon
    public const string LITER                    = 'LTR' ; // Liter
    public const string MILLILITER               = 'MLT' ; // Milliliter
    public const string US_GALLON                = 'GLL' ; // US Gallon

    // =====================================================================
    // Energy Units
    // =====================================================================

    public const string CALORIE                  = 'R4' ; // Calorie
    public const string JOULE                    = 'JOU' ; // Joule
    public const string KILOCALORIE              = 'E14' ; // Kilocalorie
    public const string KILOJOULE                = 'KJO' ; // Kilojoule
    public const string KILOWATT_HOUR            = 'KWH' ; // Kilowatt-Hour

    // =====================================================================
    // Mass Units (Weight)
    // =====================================================================

    public const string CARAT                    = 'CTM' ; // Carat
    public const string GRAM                     = 'GRM' ; // Gram
    public const string KILOGRAM                 = 'KGM' ; // Kilogram
    public const string METRIC_TON               = 'TNE' ; // Metric Ton
    public const string MILLIGRAM                = 'MGM' ; // Milligram
    public const string OUNCE                    = 'ONZ' ; // Ounce
    public const string POUND                    = 'LBR' ; // Pound

    // =====================================================================
    // Temperature Units
    // =====================================================================

    public const string CELSIUS                  = 'CEL' ; // Degree Celsius
    public const string FAHRENHEIT               = 'FAH' ; // Degree Fahrenheit
    public const string KELVIN                   = 'KEL' ; // Kelvin

    // =====================================================================
    // Length Units
    // =====================================================================

    public const string CENTIMETER               = 'CMT' ; // Centimeter
    public const string FOOT                     = 'FOT' ; // Foot
    public const string HECTOMETER               = 'HMT' ; // Hectometer
    public const string INCH                     = 'INH' ; // Inch
    public const string KILOMETER                = 'KMT' ; // Kilometer
    public const string METER                    = 'MTR' ; // Meter
    public const string MILE                     = 'SMI' ; // Mile
    public const string MILLIMETER               = 'MMT' ; // Millimeter
    public const string YARD                     = 'YRD' ; // Yard

    // =====================================================================
    // Time Units
    // =====================================================================

    public const string DAY                      = 'DAY' ; // Day
    public const string HOUR                     = 'HUR' ; // Hour
    public const string MINUTE                   = 'MIN' ; // Minute
    public const string MONTH                    = 'MON' ; // Month
    public const string SECOND                   = 'SEC' ; // Second
    public const string WEEK                     = 'WEE' ; // Week
    public const string YEAR                     = 'ANN' ; // Year

    // =====================================================================
    // Quantity Units (Unités de quantité)
    // =====================================================================

    public const string DOZEN                    = 'DZN' ; // Dozen
    public const string GROSS                    = 'GRO' ; // Gross
    public const string HUNDRED                  = 'CEN' ; // Hundred
    public const string PAIR                     = 'PR' ; // Pair
    public const string PIECE                    = 'H87' ; // Piece
    public const string TEN_PAIRS                = 'TPR' ; // Ten Pairs
    public const string THOUSAND                 = 'MIL' ; // Thousand
    public const string UNIT                     = 'C62' ; // Unit

    // =====================================================================
    // Density Units
    // =====================================================================

    public const string KILOGRAM_PER_CUBIC_METER = 'KMQ' ; // Kilogram per cubic metre

    // =====================================================================
    // Percentage and Ratio Units
    // =====================================================================

    public const string PARTS_PER_MILLION        = '59' ; // Parts Per Million
    public const string PERCENT                  = 'P1' ; // Percent
    public const string PER_THOUSAND             = 'NX' ; // Per Thousand

    // =====================================================================
    // Generic / Dimensionless Units & Factors
    // =====================================================================

    public const string SCORE                    = 'SCO' ; // Score

    // =====================================================================
    // Private
    // =====================================================================

    private static ?array $NAMES = null ;
    private static ?array $SYMBOLS = null ;

    // =====================================================================
    // Methods
    // =====================================================================

    /**
     * Returns the official UN/CEFACT name for a given code.
     * @param string $code The UN/CEFACT code (e.g., 'KGM').
     * @return string|null The UN/CEFACT name (e.g., 'Kilogram') or null if not found.
     */
    public static function getName( string $code ): ?string
    {
        if( static::$NAMES === null )
        {
            static::$NAMES = MeasureName::getAll() ;
        }
        return static::$NAMES[ self::getConstant( $code ) ] ?? null;
    }

    /**
     * Returns the official UN/CEFACT symbol for a given code.
     * @param string $code The UN/CEFACT code (e.g., 'KGM').
     * @return string|null The UN/CEFACT symbol (e.g., 'kg') or null if not found.
     */
    public static function getSymbol( string $code ): ?string
    {
        if( static::$SYMBOLS === null )
        {
            static::$SYMBOLS = MeasureSymbol::getAll() ;
        }
        return static::$SYMBOLS[ self::getConstant( $code ) ] ?? null;
    }

    /**
     * Returns the code matching a specific unit name.
     * @param string $name The UN/CEFACT name (e.g., 'Kilogram').
     * @return string|null The UN/CEFACT code (e.g., 'KGM') or null if not found.
     */
    public static function getFromName( string $name ): ?string
    {
        return MeasureName::getCode( $name ) ;
    }

    /**
     * Returns the code matching a specific unit symbol.
     * @param string $symbol The UN/CEFACT symbol (e.g., 'kg').
     * @return string|null The UN/CEFACT code (e.g., 'KGM') or null if not found.
     */
    public static function getFromSymbol( string $symbol ): ?string
    {
        return MeasureSymbol::getCode( $symbol ) ;
    }

    /**
     * Reset the internal cache of the static methods.
     * @return void
     */
    public static function resetCaches(): void
    {
        static::internalResetCaches();
        static::$NAMES = null ;
        static::$SYMBOLS = null ;
    }
}
